spring:
  mybatis:
    mapper-locations: "classpath*:**/mapper.xml"
    configuration-properties:
      aggressiveLazyLoading: false
      lazyLoadingEnabled: true
      lazyLoadTriggerMethods: ""
      mapUnderscoreToCamelCase: true
  h2:
    console: 
      path: /console
      enabled: true
      
logging:
  level:
    org.springframework.boot: DEBUG
    sample.springboot.mybatis: DEBUG
  
